### ISSUE TITLE
Error: [CORE - LIT-STATIC-PROPERTIES]: Looks like you've hit an error in the core library.

### ISSUE THREAD

**Issue by domoskanonos** [open-wc/custom-elements-manifest#163]
NPM command: custom-elements-manifest analyze --outdir public/ --litelement --dev

with node version 14.17.0 everything works fine, version 16.14.2 broken with error:

TypeError: Cannot read properties of undefined (reading 'push')
    at mapClassMember (file:///C:/machineroom/git/ui-blueprint-webcomponent/blueprint-frontend/node_modules/@custom-elements-manifest/analyzer/src/features/analyse-phase/creators/createClass.js:242:27)
    at file:///C:/machineroom/git/ui-blueprint-webcomponent/blueprint-frontend/node_modules/@custom-elements-manifest/analyzer/src/features/analyse-phase/creators/createClass.js:211:35
    at Array.forEach (<anonymous>)
    at visitNode (file:///C:/machineroom/git/ui-blueprint-webcomponent/blueprint-frontend/node_modules/@custom-elements-manifest/analyzer/src/features/analyse-phase/creators/createClass.js:211:12)
    at visitNodes (C:\machineroom\git\ui-blueprint-webcomponent\blueprint-frontend\node_modules\@custom-elements-manifest\analyzer\node_modules\typescript\lib\typescript.js:29004:30)
    at Object.forEachChild (C:\machineroom\git\ui-blueprint-webcomponent\blueprint-frontend\node_modules\@custom-elements-manifest\analyzer\node_modules\typescript\lib\typescript.js:29316:21)
    at visitNode (file:///C:/machineroom/git/ui-blueprint-webcomponent/blueprint-frontend/node_modules/@custom-elements-manifest/analyzer/src/features/analyse-phase/creators/createClass.js:216:8)
    at getDefaultValuesFromConstructorVisitor (file:///C:/machineroom/git/ui-blueprint-webcomponent/blueprint-frontend/node_modules/@custom-elements-manifest/analyzer/src/features/analyse-phase/creators/createClass.js:200:3)
    at analyzePhase (file:///C:/machineroom/git/ui-blueprint-webcomponent/blueprint-frontend/node_modules/@custom-elements-manifest/analyzer/src/features/framework-plugins/lit/static-properties.js:75:11)
    at file:///C:/machineroom/git/ui-blueprint-webcomponent/blueprint-frontend/node_modules/@custom-elements-manifest/analyzer/src/create.js:104:23

    at withErrorHandling (file:///C:/machineroom/git/ui-blueprint-webcomponent/blueprint-frontend/node_modules/@custom-elements-manifest/analyzer/src/utils/index.js:67:11)
    at file:///C:/machineroom/git/ui-blueprint-webcomponent/blueprint-frontend/node_modules/@custom-elements-manifest/analyzer/src/create.js:103:7
    at Array.forEach (<anonymous>)
    at visitNode (file:///C:/machineroom/git/ui-blueprint-webcomponent/blueprint-frontend/node_modules/@custom-elements-manifest/analyzer/src/create.js:102:19)
    at visitNodes (C:\machineroom\git\ui-blueprint-webcomponent\blueprint-frontend\node_modules\@custom-elements-manifest\analyzer\node_modules\typescript\lib\typescript.js:29004:30)
    at Object.forEachChild (C:\machineroom\git\ui-blueprint-webcomponent\blueprint-frontend\node_modules\@custom-elements-manifest\analyzer\node_modules\typescript\lib\typescript.js:29241:24)
    at visitNode (file:///C:/machineroom/git/ui-blueprint-webcomponent/blueprint-frontend/node_modules/@custom-elements-manifest/analyzer/src/create.js:108:8)
    at visitNode (C:\machineroom\git\ui-blueprint-webcomponent\blueprint-frontend\node_modules\@custom-elements-manifest\analyzer\node_modules\typescript\lib\typescript.js:28995:24)
    at Object.forEachChild (C:\machineroom\git\ui-blueprint-webcomponent\blueprint-frontend\node_modules\@custom-elements-manifest\analyzer\node_modules\typescript\lib\typescript.js:29125:21)
    at visitNode (file:///C:/machineroom/git/ui-blueprint-webcomponent/blueprint-frontend/node_modules/@custom-elements-manifest/analyzer/src/create.js:108:8)

**Comment by domoskanonos** [comment]
import {LitElement, TemplateResult, html} from "lit";
import {customElement, property} from "lit/decorators.js";
import {environment} from "../environments/environment";
import {OpenidService} from "../service/openid-service";

@customElement("si-ui-blueprint-webcomponent")
export class SiUiBlueprintWebcomponent extends LitElement {

    @property({type: String})
    status: string = "success";

    public render(): TemplateResult {
        return html`
Something to render            


        `;
    }

    private login(): void {
        OpenidService.init();
    }

    private newListItem(text: string) {
        return html`
            <span style="display:flex;padding-top: var(--space-50);">
            <sdasi-icon
                    style="--sdasi-icon-fill: var(--color-success-100); width:24px; padding-right: var(--space-100);"
                    icon="FUNCTIONAL_CHECKMARK"></sdasi-icon>
            ${text}
            </span>`;
    }

}

**Comment by thepassle** [comment]
Im not able to reproduce locally or in the [playground](https://custom-elements-manifest.netlify.app/?source=CmltcG9ydCB7TGl0RWxlbWVudCwgVGVtcGxhdGVSZXN1bHQsIGh0bWx9IGZyb20gImxpdCI7CmltcG9ydCB7Y3VzdG9tRWxlbWVudCwgcHJvcGVydHl9IGZyb20gImxpdC9kZWNvcmF0b3JzLmpzIjsKaW1wb3J0IHtlbnZpcm9ubWVudH0gZnJvbSAiLi4vZW52aXJvbm1lbnRzL2Vudmlyb25tZW50IjsKaW1wb3J0IHtPcGVuaWRTZXJ2aWNlfSBmcm9tICIuLi9zZXJ2aWNlL29wZW5pZC1zZXJ2aWNlIjsKCkBDdXN0b21FbGVtZW50KCJzaS11aS1ibHVlcHJpbnQtd2ViY29tcG9uZW50IikKZXhwb3J0IGNsYXNzIFNpVWlCbHVlcHJpbnRXZWJjb21wb25lbnQgZXh0ZW5kcyBMaXRFbGVtZW50IHsKCkBwcm9wZXJ0eSh7dHlwZTogU3RyaW5nfSkKc3RhdHVzOiBzdHJpbmcgPSAic3VjY2VzcyI7CgpwdWJsaWMgcmVuZGVyKCk6IFRlbXBsYXRlUmVzdWx0IHsKICAgIHJldHVybiBodG1sYFNvbWV0aGluZyB0byByZW5kZXIgYDsKfQoKcHJpdmF0ZSBsb2dpbigpOiB2b2lkIHsKICAgIAp9Cgpwcml2YXRlIG5ld0xpc3RJdGVtKHRleHQ6IHN0cmluZykgewogICAgcmV0dXJuIGh0bWxgCiAgICAgICBzb21ldGhpbmdgOwogICAgfQp9Cgo%3D&library=litelement)
![image](https://user-images.githubusercontent.com/17054057/162911239-2752e613-566d-4dfb-ae7f-bc8aff910cec.png)

Do note that you're importing 
```js
import {customElement, property} from "lit/decorators.js";
```

but using it with a capital:
```js
@CustomElement("si-ui-blueprint-webcomponent")
```

**Comment by domoskanonos** [comment]
@CustomElement -> git automatically capitalized it

**Comment by domoskanonos** [comment]
in my code it's lowercase "c"

**Comment by domoskanonos** [comment]
ok i will try to find out where the problem is and i will report here. If i remove "--litElement" flag it works...

**Comment by domoskanonos** [comment]
exact environment : node: v16.14.2, npm: 8.5.0

**Comment by valentindiehl** [comment]
@domoskanonos Have you found a solution for this? I'm having the same issue, but I'm trying for days to find the source since it randomly appeared without really changing or updating anything. 

As soon as I find a minimal example without 300 lines of code, I'll post it here.

**Comment by valentindiehl** [comment]
To add to this: The error already happens when running "npm install", not even while transpiling with run/build

**Comment by DeepakJY97SF** [comment]
I fixed this issue in the createClass.js by checking for classTemplate.members existence and initialize it with empty array in undefined

old:
```
  if (!existingMember) {
    if (hasIgnoreJSDoc(statement)) return;
    if (isBindCall(statement)) return;

    existingMember = {
      kind: 'field',
      name: expression?.left?.name?.getText(),
    }
    classTemplate.members.push(existingMember);
  }
```
new:
```
  if (!existingMember) {
    if (hasIgnoreJSDoc(statement)) return;
    if (isBindCall(statement)) return;

    existingMember = {
      kind: 'field',
      name: expression?.left?.name?.getText(),
    }
    if(!classTemplate.members){
      classTemplate.members = [];
    }
    classTemplate.members.push(existingMember);
  }
```
I tried to push a fix branch to create a pullrequest, but I don't have the rights

**Comment by KameronKales** [comment]
I had this issue (independent of which node version I was running, i tried 14 and 16). 

I was able to fix by being verify specific about what code to include via --glob. 

For a project im working on 

This works: 

```cem analyze --litelement --globs packages/*/* --exclude packages/*/dist```

This does not 

```cem analyze --litelement  --exclude packages/*/dist```

and this does not 

```cem analyze --litelement --globs packages/*/* ```

Obviously YMMV but changing this command got me up and running again. Im assuming there is some code in my project that is causing the issue and I should have been using globs all along
